version: "3"

services:
  ray-head:
    build:
      context: .
      target: ray-base

    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
    env_file:
      - .env
    command: bash -c "ray start --head --dashboard-port=${DASHBOARDPORT} --port=${REDISPORT} --dashboard-host=0.0.0.0 --redis-password=${REDISPASSWORD} --block"
    shm_size: 2g
    volumes:
      # Mount notebooks dir
      - ./notebooks:/notebooks
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'

  ray-worker:
    build:
      context: .
      target: ray-base
    depends_on: 
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDISPORT} --redis-password=${REDISPASSWORD} --num-cpus=${NUM_CPU_WORKER} --block" 
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 1
          memory: '2g'

  ray-notebook:
    build:
      context: .
      target: ray-notebook
    depends_on:
      - ray-head
    ports:
      - "8888:8888"
    volumes:
      # Mount notebooks dir
      - ./notebooks:/home/jovyan/notebooks
    env_file:
      - .env
    command: bash -c "jupyter lab --ip=0.0.0.0 --no-browser --allow-root"
